# Generated by Django 5.0.4 on 2024-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('service', models.CharField(max_length=50)),
                ('budget', models.IntegerField(null=True)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
