# Generated by Django 5.0.4 on 2024-04-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
